Dev login
PlantsMTL/frontend pull request #3
Opened 2023-04-28 17:45 UTC by mariuo

Created Login Page layout based on https://www.figma.com/file/rAn3Ofr2PYWUK1Sht8R5jc/PlantsMTL?node-id=0-1&t=akNX4SJ2gmT1gSq7-0

2023-04-29 01:17 UTC, brunosantanaa commented on src/App.css
> +    background-color: #F2F9F1;
Poderiamos abstrair essas cores em variáveis (Levar a mesma ideia para fontes e afastamentos). Criando um arquivo com com definicoes globais de tema.

2023-04-29 01:20 UTC, brunosantanaa commented on src/components/ImgButtonIcon/styles.scss
> +    font-size: 16px;
A definicao de tamanho de fonte, tambem poderia estar nos padroes globais de tema.

2023-04-29 01:26 UTC, brunosantanaa requested changes
De uma maneira geral seria criar um arquivo de estilo para o tema, com definicao de cores, parametros de texto e espacamentos padrao(Padding base) para evitar repeticoes e possiveis erros.

2023-04-29 14:18 UTC, mariuo commented
All the colors variables were created in App.css, and I made all necessaries changes.

2023-05-01 12:22 UTC, paivajulia approved these changes

2023-05-01 12:23 UTC, paivajulia approved these changes

2023-05-01 12:39 UTC, brunosantanaa approved these changes

2023-05-01 18:29 UTC, merged